language: go
sudo: false
go:
  - 1.6
env:
  - SPREAD="./pkg/... ./cli/... ./cmd/..."

go_import_path: rsprd.com/spread

install:
  # install golint
  - go get -u github.com/golang/lint/golint

before_script:
  # Fix to get around issue with Kubernetes not
  # loading types from rewritten imports
  - export GO15VENDOREXPERIMENT=0
  - cp -r ./vendor/* $GOPATH/src

  - go vet $SPREAD

script:
  - go test -v $SPREAD

after_success:
  - |
    while IFS=' ' read -ra PKG; do
      for i in "${PKG[@]}"; do
        echo "Running golint on $i:"
        golint $i
        printf "#########################\n\n\n"
      done
    done <<< "$SPREAD"
